FROM bellsoft/liberica-openjdk-alpine:11.0.12-7

#RUN apt-get update && apt-get install -y --no-install-recommends libfontconfig1 curl ftp && rm -rf /var/lib/apt/lists/*

EXPOSE 8080

WORKDIR /home/avwebservice

ARG DEPENDENCY=build/dependency
COPY ${DEPENDENCY}/BOOT-INF/lib /home/avwebservice/app/lib
COPY ${DEPENDENCY}/META-INF /home/avwebservice/app/META-INF
COPY ${DEPENDENCY}/BOOT-INF/classes /home/avwebservice/app
RUN chown -R 1001:0 /home/avwebservice && \
    chmod -R g=u /home/avwebservice

USER 1001
#Log4j 2 CVE-2021-44228
ENV LOG4J_FORMAT_MSG_NO_LOOKUPS=true
ENTRYPOINT ["java","-XX:MaxRAMPercentage=80.0", "-noverify", "-XX:TieredStopAtLevel=1", "-cp","app:app/lib/*","ch.so.agi.cadastre.webservice.CadastreWebServiceApplication"]
